# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Manual Build
on:
  workflow_dispatch:
    inputs:
      build-type:
        description: |
          The type of build to create.

          Valid options are:

           * `production` for a production build.
           * `development` for a development build.

          Defaults to `production`.
        type: choice
        required: false
        options:
          - production
          - development
        default: development
      upload-artifacts:
        description: |
          Whether to upload artifacts.

          Defaults to `true`.
        type: boolean
        required: false
        default: true
      artifact-retention-duration:
        description: |
          The length of time, in days, to retain uploaded artifacts for.

          If set to `0`, defaults to the value configured for the repository.

          Defaults to `0`.
        type: number
        required: false
        default: 0
jobs:
  manual_build:
    name: Manual Build
    permissions:
      #-- To clone the repository
      contents: read
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{github.ref}}
      build-type: ${{inputs.build-type}}
      upload-artifacts: ${{inputs.upload-artifacts}}
      artifact-retention-duration: ${{inputs.artifact-retention-duration}}
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
