# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Manual Lint
on:
  workflow_dispatch:
jobs:
  manual_lint:
    name: Manual Lint
    permissions:
      #-- To clone the repository
      contents: read
    uses: ./.github/workflows/lint.yaml
    with:
      ref: ${{github.ref}}
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
