# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Manual Test
on:
  workflow_dispatch:
    inputs:
      upload-artifacts:
        description: |
          Whether to upload artifacts.

          Defaults to `true`.
        type: boolean
        required: false
        default: true
      artifact-retention-duration:
        description: |
          The length of time, in days, to retain uploaded artifacts for.

          If set to `0`, defaults to the value configured for the repository.

          Defaults to `0`.
        type: number
        required: false
        default: 0
jobs:
  manual_test:
    name: Manual Test
    permissions:
      #-- To clone the repository
      contents: read
    uses: ./.github/workflows/test.yaml
    with:
      ref: ${{github.ref}}
      upload-artifacts: ${{inputs.upload-artifacts}}
      artifact-retention-duration: ${{inputs.artifact-retention-duration}}
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
