name: On Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    permissions:
      #-- To clone the repository
      contents: read
    strategy:
      fail-fast: true
      matrix:
        build-type:
          - production
          - development
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{github.ref}}
      build-type: ${{matrix.build-type}}
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
  test:
    name: Test
    permissions:
      #-- To clone the repository
      contents: read
    uses: ./.github/workflows/test.yaml
    with:
      ref: ${{github.ref}}
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
  lint:
    name: Lint
    permissions:
      #-- To clone the repository
      contents: read
    uses: ./.github/workflows/lint.yaml
    with:
      ref: ${{github.ref}}
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
