name: On Schedule
on:
  schedule:
    - cron: '0 12 * * 3'
jobs:
  codeql:
    name: CodeQL
    permissions:
      #-- To clone the repository
      contents: read
      #-- To create security issues
      security-events: write
    uses: ./.github/workflows/codeql.yaml
    with:
      ref: ${{github.ref}}
      sha: ${{github.sha}}
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
